export const POST_FOLDER_START = 'POST_FOLDER_START';
export const POST_FOLDER_SUCCESS = 'POST_FOLDER_SUCCESS';
export const POST_FOLDER_FAIL = 'POST_FOLDER_FAIL';

export const GET_MACHETE_START = 'GET_MACHETE_START';
export const GET_MACHETE_SUCCESS = 'GET_MACHETE_SUCCESS';
export const GET_MACHETE_FAIL = 'GET_MACHETE_FAIL';

export const GET_FOLDERS_START = 'GET_FOLDERS_START';
export const GET_FOLDERS_SUCCESS = 'GET_FOLDERS_SUCCESS';
export const GET_FOLDERS_FAIL = 'GET_FOLDERS_FAIL';